---
################################################################################
## Tool options                                                             #
#################################################################################
# scripts_path: Path to the scripts folder of the gblaster package
# blast_exe : Path to the blastn executable
# bedtools : Path to bedtools executable
#
scripts_path: 'Path to the scripts dir'
blast_exe: 'Path to the blast_exe'
bedtools: 'Path to the bedtools exe' 

################################################################################
## Input options                                                             #
#################################################################################
# ref : Path to Reference fasta file
# gff : GFF3 file corresponding to the reference
# repeats : Path to the repeats fasta file
# query: Path to the query fastas file which has no annotation. UPTO: 10 files allowed
#

ref: 'Path to the reference fasta file'
gff: 'Path to the reference gff file'
repeats: 'Path to the repeats file'
outdir: 'Path to the outdir'
logddir: 'Path to the logsdir'
query:
 - 'Path to query 1 fasta'
 - 'Path to query 2 fasta'
 - 'Path to query 3 fasta'
